spring.application.name=md4-ss12

spring.datasource.url=jdbc:mysql://localhost:3306/md4_ss12_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Nguyenthuy92@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


